### PR TITLE
feat(entrypoint-readonly): remove block producer wallet config

### PR DESCRIPTION
**Pull request by zeroqn**
related pr
- https://github.com/nervosnetwork/godwoken/pull/768

### CODE REVIEW

**Comment by keroro520** [comment]
CI fails. Might need a new version of docker image?

**Comment by keroro520** [comment]
> I can't find web3 log from https://github.com/RetricSu/godwoken-kicker/suites/7435344993/artifacts/303978125 kicker-logs.zip.

Godwoken fails to start, so Web3 has never started because of the depends.condition:

```
ERROR: for wait-until-godwoken-v0-becomes-healthy  Container "e4715a162b7c" is unhealthy.
```

**Comment by zeroqn** [comment]
Yes... require godwoken v1.4.2.

**Comment by zeroqn** [comment]
Ok, rebased.

**Review by RetricSu — APPROVED** [review]

**Review by keroro520 — APPROVED** [review]

**Pull request merged**
