### PR TITLE
Feat/posix compliant

### PR DESCRIPTION
**Pull request by sleepyyj**
Linked to this issue. https://github.com/RetricSu/godwoken-kicker/issues/310

### CODE REVIEW

**Review by keroro520 — CHANGES_REQUESTED** [review]
There is one staled code: https://github.com/RetricSu/godwoken-kicker/blob/daa5e2c38f851b7e2994b27c73440d32b99bbb0f/kicker#L123

**Comment by sleepyyj** [comment]
> There is one staled code:
> 
> https://github.com/RetricSu/godwoken-kicker/blob/daa5e2c38f851b7e2994b27c73440d32b99bbb0f/kicker#L123
> 
> @sleepyyj

fixed

**Comment by sleepyyj** [comment]
It would be nice if there was a test script that could be run locally

**Comment by keroro520** [comment]
> It would be nice if there was a test script that could be run locally

Usualy, simply `./kicker start` is enough to test.
However, kicker supports manual-build functional, which is internal use and CI use only.
I agree that it would be nice  if there was a test script that could be run locally, but it is very low priority :D

**Pull request merged**
